# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('ivdoctr_rcpp_hello', PACKAGE = 'ivdoctr')
}

rinvwish <- function(n, v, S) {
    .Call('ivdoctr_rinvwish', PACKAGE = 'ivdoctr', n, v, S)
}

