# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

classicalSampler <- function(Rho_vech, L, n_M, K_L = 0.2, K_U = 1, Rxsu_L = -0.9, Rxsu_U = 0.9, Rzu_L = -0.9, Rzu_U = 0.9, xRsq = 0, weight_sampling = TRUE, Su_U_infty = TRUE, Su_L = 0, Su_U = 100) {
    .Call('ivdoctr_classicalSampler', PACKAGE = 'ivdoctr', Rho_vech, L, n_M, K_L, K_U, Rxsu_L, Rxsu_U, Rzu_L, Rzu_U, xRsq, weight_sampling, Su_U_infty, Su_L, Su_U)
}

#' Half-vectorization of a symmetric matrix
#'
#' @param M An n by n symmetric matrix.
#' @return A column vector containing the vech of M, i.e.
#' the n * (n + 1) / 2 unique elements of M.
#' @details Throws an error if M is not square, but does not test if M is
#' symmetric. Elements above the main diagonal are simply ignored.
#' @examples
#' M <- matrix(c(11, 12, 13, 14,
#'               12, 22, 23, 24,
#'               13, 23, 33, 34,
#'               14, 24, 34, 44), 4, 4, byrow = TRUE)
#' vech(M)
vech <- function(M) {
    .Call('ivdoctr_vech', PACKAGE = 'ivdoctr', M)
}

#' Convert Half-vectorization to symmetric matrix
#'
#' @param v A numeric vector with n * (n + 1) / 2 elements.
#' @param dim An integer indicating the dimension of the resulting square,
#' symmetric matrix.
#' @return The n by n symmetric matrix whose half-vectorization is v.
#' @details Throws an error if dim does not correspond to the length of v.
#' @examples
#' v <- c(11:14, 22:24, 33:34, 44)
#' devech(v, 4)
devech <- function(v, dim) {
    .Call('ivdoctr_devech', PACKAGE = 'ivdoctr', v, dim)
}

#' Simulate draws from the inverse Wishart distribution
#'
#' @param n An integer, the number of draws.
#' @param v An integer, the degrees of freedom of the distribution.
#' @param S A numeric matrix, the scale matrix of the distribution.
#' @return A numeric array of matrices, each of which is one simulation draw.
#' @details Employs the Bartlett Decomposition (Smith & Hocking 1972).
#' Output exactly matches that of riwish from the MCMCpack package if the same
#' random seed is used.
#' @examples
#' M <- matrix(c(1, 0.5, 0.5, 1), 2, 2)
#' rinvwish(5, 10, M)
rinvwish <- function(n, v, S) {
    .Call('ivdoctr_rinvwish', PACKAGE = 'ivdoctr', n, v, S)
}

