# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate draws from the inverse Wishart distribution
#' @param n An integer, the number of draws.
#' @param v An integer, the degrees of freedom of the distribution.
#' @param S A numeric matrix, the scale matrix of the distribution.
#' @return A numeric array of matrices, each of which is one simulation draw.
#' @details Employs the Bartlett Decomposition (Smith & Hocking 1972).
#' Output exactly matches that of riwish from the MCMCpack package if the same
#' random seed is used.
rinvwish <- function(n, v, S) {
    .Call(`_ivdoctr_rinvwish`, n, v, S)
}

